version: "3"
services:
    db:
        image: mysql:8.0.20
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file: .env
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - db-datavolume:/var/lib/mysql
            - ./mysql:/etc/mysql/conf.d
            - ${MYSQL_BACKUP_LOCATION}:/opt/mysql/backup
        ports:
            - "3306:3306"
        labels:
            - traefik.enable=false
    traccar:
        image: ${TRACCAR_IMAGE}
        container_name: traccar
        depends_on:
            - db
        restart: always
        volumes:
            - ./traccar/conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro
            - /var/log/traccar:/opt/traccar/logs:rw
        ports:
            - "5000-5150:5000-5150"
            - "8082:8082"
        labels:
            - traefik.http.routers.traccar.rule=Host(`web.${DOMAIN}`)
            - traefik.http.services.traccar_web.loadbalancer.server.port=8082
    rev_proxy:
        image: traefik:v2.2
        container_name: rev_proxy
        restart: always
        env_file: .env
        ports:
          - "80:80"
          - "443:443"
          - "8080:8080"
        labels:
          - traefik.http.routers.api.rule=Host(`proxy.${DOMAIN}`)
          - traefik.http.routers.api.service=api@internal
          - traefik.http.routers.api.middlewares=traefik-forward-auth
        volumes:
          - ./traefik/traefik.toml:/traefik.toml
          - ./traefik/acme.json:/acme.json
          - /var/log/traefik:/logs
          - /var/run/docker.sock:/var/run/docker.sock

    traefik-forward-auth:
        image: thomseddon/traefik-forward-auth:2
        container_name: traefik_forward_auth
        restart: always
        environment:
        - DEFAULT_PROVIDER=${DEFAULT_PROVIDER}
        - PROVIDERS_OIDC_ISSUER_URL=${PROVIDERS_OIDC_ISSUER_URL}
        - PROVIDERS_OIDC_CLIENT_ID=${PROVIDERS_OIDC_CLIENT_ID}
        - PROVIDERS_OIDC_CLIENT_SECRET=${PROVIDERS_OIDC_CLIENT_SECRET}
        - SECRET=${SECRET}
        - INSECURE_COOKIE=true
        - LOG_LEVEL=error
        labels:
        - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
        - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
        - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
volumes:
    db-datavolume:
